#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 67
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 6

enum {
  aux_sym_comment_token1 = 1,
  anon_sym_POUND = 2,
  aux_sym__variable_command_token1 = 3,
  aux_sym__variable_command_token2 = 4,
  sym_command_identifier = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_DOLLAR = 8,
  sym_word = 9,
  sym__full_word = 10,
  sym__semicolon = 11,
  sym_source_file = 12,
  sym__command_option = 13,
  sym_command = 14,
  sym_comment = 15,
  sym_variable_declaration = 16,
  sym__command_name = 17,
  sym__variable_command = 18,
  sym__block_choice = 19,
  sym_block = 20,
  sym_variable_reference = 21,
  sym_string = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_command_repeat1 = 24,
  aux_sym_string_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_POUND] = "#",
  [aux_sym__variable_command_token1] = "command_identifier",
  [aux_sym__variable_command_token2] = "command_identifier",
  [sym_command_identifier] = "command_identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOLLAR] = "$",
  [sym_word] = "word",
  [sym__full_word] = "_full_word",
  [sym__semicolon] = "_semicolon",
  [sym_source_file] = "source_file",
  [sym__command_option] = "_command_option",
  [sym_command] = "command",
  [sym_comment] = "comment",
  [sym_variable_declaration] = "command",
  [sym__command_name] = "_command_name",
  [sym__variable_command] = "_variable_command",
  [sym__block_choice] = "_block_choice",
  [sym_block] = "block",
  [sym_variable_reference] = "variable_reference",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym__variable_command_token1] = sym_command_identifier,
  [aux_sym__variable_command_token2] = sym_command_identifier,
  [sym_command_identifier] = sym_command_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_word] = sym_word,
  [sym__full_word] = sym__full_word,
  [sym__semicolon] = sym__semicolon,
  [sym_source_file] = sym_source_file,
  [sym__command_option] = sym__command_option,
  [sym_command] = sym_command,
  [sym_comment] = sym_comment,
  [sym_variable_declaration] = sym_command,
  [sym__command_name] = sym__command_name,
  [sym__variable_command] = sym__variable_command,
  [sym__block_choice] = sym__block_choice,
  [sym_block] = sym_block,
  [sym_variable_reference] = sym_variable_reference,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__variable_command_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__variable_command_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_command_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym__full_word] = {
    .visible = false,
    .named = true,
  },
  [sym__semicolon] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__command_option] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__command_name] = {
    .visible = false,
    .named = true,
  },
  [sym__variable_command] = {
    .visible = false,
    .named = true,
  },
  [sym__block_choice] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_name = 1,
  field_value = 2,
  field_variable_declaration = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
  [field_variable_declaration] = "variable_declaration",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_variable_declaration, 0, .inherited = true},
  [1] =
    {field_variable_declaration, 0},
  [2] =
    {field_variable_declaration, 0, .inherited = true},
    {field_variable_declaration, 1, .inherited = true},
  [4] =
    {field_name, 1},
    {field_value, 2},
  [6] =
    {field_variable_declaration, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 2,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 6,
  [10] = 8,
  [11] = 5,
  [12] = 12,
  [13] = 12,
  [14] = 7,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 18,
  [19] = 18,
  [20] = 16,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 21,
  [25] = 25,
  [26] = 26,
  [27] = 25,
  [28] = 23,
  [29] = 26,
  [30] = 22,
  [31] = 31,
  [32] = 32,
  [33] = 32,
  [34] = 31,
  [35] = 35,
  [36] = 35,
  [37] = 32,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 40,
  [42] = 26,
  [43] = 25,
  [44] = 44,
  [45] = 21,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 48,
  [51] = 46,
  [52] = 44,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 23,
  [57] = 49,
  [58] = 55,
  [59] = 47,
  [60] = 60,
  [61] = 54,
  [62] = 53,
  [63] = 63,
  [64] = 63,
  [65] = 63,
  [66] = 66,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(2);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym__variable_command_token1);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__variable_command_token2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(15);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(12);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_command_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__full_word);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__semicolon);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [aux_sym__variable_command_token1] = ACTIONS(1),
    [aux_sym__variable_command_token2] = ACTIONS(1),
    [sym_command_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym__semicolon] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(66),
    [sym__command_option] = STATE(58),
    [sym_command] = STATE(58),
    [sym_comment] = STATE(58),
    [sym_variable_declaration] = STATE(61),
    [sym__command_name] = STATE(10),
    [sym__variable_command] = STATE(34),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_comment_token1] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
  },
  [2] = {
    [sym__command_option] = STATE(55),
    [sym_command] = STATE(55),
    [sym_comment] = STATE(55),
    [sym_variable_declaration] = STATE(54),
    [sym__command_name] = STATE(8),
    [sym__variable_command] = STATE(31),
    [sym_variable_reference] = STATE(39),
    [sym_string] = STATE(65),
    [aux_sym_source_file_repeat1] = STATE(20),
    [aux_sym_string_repeat1] = STATE(39),
    [aux_sym_comment_token1] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(13),
    [anon_sym_DOLLAR] = ACTIONS(15),
    [sym__full_word] = ACTIONS(17),
  },
  [3] = {
    [sym__command_option] = STATE(55),
    [sym_command] = STATE(55),
    [sym_comment] = STATE(55),
    [sym_variable_declaration] = STATE(54),
    [sym__command_name] = STATE(8),
    [sym__variable_command] = STATE(31),
    [sym_variable_reference] = STATE(39),
    [sym_string] = STATE(64),
    [aux_sym_source_file_repeat1] = STATE(16),
    [aux_sym_string_repeat1] = STATE(39),
    [aux_sym_comment_token1] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_DOLLAR] = ACTIONS(15),
    [sym__full_word] = ACTIONS(17),
  },
  [4] = {
    [sym__command_option] = STATE(55),
    [sym_command] = STATE(55),
    [sym_comment] = STATE(55),
    [sym_variable_declaration] = STATE(54),
    [sym__command_name] = STATE(8),
    [sym__variable_command] = STATE(31),
    [sym_variable_reference] = STATE(39),
    [sym_string] = STATE(63),
    [aux_sym_source_file_repeat1] = STATE(17),
    [aux_sym_string_repeat1] = STATE(39),
    [aux_sym_comment_token1] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(15),
    [sym__full_word] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      sym_word,
    ACTIONS(33), 1,
      sym__semicolon,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
    STATE(13), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [26] = 7,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_DOLLAR,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      sym_word,
    ACTIONS(41), 1,
      sym__semicolon,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
    STATE(14), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [52] = 7,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(51), 1,
      sym_word,
    ACTIONS(53), 1,
      sym__semicolon,
    ACTIONS(43), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
    STATE(12), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [78] = 7,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(57), 1,
      anon_sym_POUND,
    ACTIONS(59), 1,
      sym_word,
    ACTIONS(61), 1,
      sym__semicolon,
    ACTIONS(55), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
    STATE(11), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [104] = 7,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(63), 1,
      sym_word,
    ACTIONS(65), 1,
      sym__semicolon,
    ACTIONS(35), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
    STATE(7), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [130] = 7,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_DOLLAR,
    ACTIONS(57), 1,
      anon_sym_POUND,
    ACTIONS(67), 1,
      sym_word,
    ACTIONS(69), 1,
      sym__semicolon,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
    STATE(5), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [156] = 7,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(51), 1,
      sym_word,
    ACTIONS(71), 1,
      sym__semicolon,
    ACTIONS(23), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
    STATE(12), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [182] = 6,
    ACTIONS(75), 1,
      anon_sym_POUND,
    ACTIONS(77), 1,
      anon_sym_LBRACE,
    ACTIONS(80), 1,
      anon_sym_DOLLAR,
    ACTIONS(83), 1,
      sym_word,
    ACTIONS(73), 3,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
      sym__semicolon,
    STATE(12), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [206] = 6,
    ACTIONS(75), 1,
      anon_sym_POUND,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(89), 1,
      anon_sym_DOLLAR,
    ACTIONS(92), 1,
      sym_word,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      sym__semicolon,
    STATE(13), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [230] = 7,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      sym_word,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(95), 1,
      sym__semicolon,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
    STATE(13), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [256] = 8,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym__command_name,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
    STATE(34), 1,
      sym__variable_command,
    STATE(61), 1,
      sym_variable_declaration,
    STATE(58), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [283] = 8,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym__command_name,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__variable_command,
    STATE(54), 1,
      sym_variable_declaration,
    STATE(55), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [310] = 8,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym__command_name,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__variable_command,
    STATE(54), 1,
      sym_variable_declaration,
    STATE(55), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [337] = 8,
    ACTIONS(103), 1,
      aux_sym_comment_token1,
    ACTIONS(106), 1,
      anon_sym_POUND,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym__command_name,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__variable_command,
    STATE(54), 1,
      sym_variable_declaration,
    STATE(55), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [364] = 8,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      aux_sym_comment_token1,
    ACTIONS(114), 1,
      anon_sym_POUND,
    STATE(10), 1,
      sym__command_name,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
    STATE(34), 1,
      sym__variable_command,
    STATE(61), 1,
      sym_variable_declaration,
    STATE(58), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [391] = 8,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym__command_name,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__variable_command,
    STATE(54), 1,
      sym_variable_declaration,
    STATE(55), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [418] = 2,
    ACTIONS(121), 1,
      anon_sym_POUND,
    ACTIONS(119), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [430] = 2,
    ACTIONS(125), 1,
      anon_sym_POUND,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [442] = 2,
    ACTIONS(129), 1,
      anon_sym_POUND,
    ACTIONS(127), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [454] = 2,
    ACTIONS(121), 1,
      anon_sym_POUND,
    ACTIONS(119), 6,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [466] = 2,
    ACTIONS(133), 1,
      anon_sym_POUND,
    ACTIONS(131), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [478] = 2,
    ACTIONS(137), 1,
      anon_sym_POUND,
    ACTIONS(135), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [490] = 2,
    ACTIONS(133), 1,
      anon_sym_POUND,
    ACTIONS(131), 6,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [502] = 2,
    ACTIONS(129), 1,
      anon_sym_POUND,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [514] = 2,
    ACTIONS(137), 1,
      anon_sym_POUND,
    ACTIONS(135), 6,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [526] = 2,
    ACTIONS(125), 1,
      anon_sym_POUND,
    ACTIONS(123), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [538] = 4,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_DOLLAR,
    ACTIONS(139), 1,
      sym_word,
    STATE(35), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [553] = 4,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(141), 1,
      anon_sym_LBRACE,
    ACTIONS(143), 1,
      sym_word,
    STATE(45), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [568] = 4,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_DOLLAR,
    ACTIONS(145), 1,
      sym_word,
    STATE(24), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [583] = 4,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_DOLLAR,
    ACTIONS(147), 1,
      sym_word,
    STATE(36), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [598] = 4,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(149), 1,
      sym_word,
    STATE(41), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [613] = 4,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_DOLLAR,
    ACTIONS(151), 1,
      sym_word,
    STATE(40), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [628] = 4,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(153), 1,
      sym_word,
    STATE(21), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [643] = 4,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    ACTIONS(157), 1,
      anon_sym_DOLLAR,
    ACTIONS(160), 1,
      sym__full_word,
    STATE(38), 2,
      sym_variable_reference,
      aux_sym_string_repeat1,
  [657] = 4,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    ACTIONS(165), 1,
      sym__full_word,
    STATE(38), 2,
      sym_variable_reference,
      aux_sym_string_repeat1,
  [671] = 3,
    ACTIONS(169), 1,
      anon_sym_POUND,
    ACTIONS(171), 1,
      sym__semicolon,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [682] = 3,
    ACTIONS(169), 1,
      anon_sym_POUND,
    ACTIONS(173), 1,
      sym__semicolon,
    ACTIONS(167), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [693] = 1,
    ACTIONS(135), 3,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym__full_word,
  [699] = 1,
    ACTIONS(131), 3,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym__full_word,
  [705] = 2,
    ACTIONS(177), 1,
      anon_sym_POUND,
    ACTIONS(175), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [713] = 1,
    ACTIONS(119), 3,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym__full_word,
  [719] = 2,
    ACTIONS(181), 1,
      anon_sym_POUND,
    ACTIONS(179), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [727] = 2,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(23), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [735] = 2,
    ACTIONS(185), 1,
      anon_sym_POUND,
    ACTIONS(183), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [743] = 2,
    ACTIONS(189), 1,
      sym_command_identifier,
    ACTIONS(187), 2,
      aux_sym__variable_command_token1,
      aux_sym__variable_command_token2,
  [751] = 2,
    ACTIONS(185), 1,
      anon_sym_POUND,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [759] = 2,
    ACTIONS(181), 1,
      anon_sym_POUND,
    ACTIONS(179), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [767] = 2,
    ACTIONS(177), 1,
      anon_sym_POUND,
    ACTIONS(175), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [775] = 2,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(43), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [783] = 2,
    ACTIONS(193), 1,
      anon_sym_POUND,
    ACTIONS(191), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [791] = 2,
    ACTIONS(197), 1,
      anon_sym_POUND,
    ACTIONS(195), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [799] = 1,
    ACTIONS(127), 3,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym__full_word,
  [805] = 2,
    ACTIONS(199), 1,
      sym_command_identifier,
    ACTIONS(187), 2,
      aux_sym__variable_command_token1,
      aux_sym__variable_command_token2,
  [813] = 2,
    ACTIONS(197), 1,
      anon_sym_POUND,
    ACTIONS(195), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [821] = 2,
    ACTIONS(25), 1,
      anon_sym_POUND,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [829] = 1,
    ACTIONS(201), 3,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
  [835] = 2,
    ACTIONS(193), 1,
      anon_sym_POUND,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [843] = 2,
    ACTIONS(45), 1,
      anon_sym_POUND,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [851] = 1,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
  [855] = 1,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
  [859] = 1,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
  [863] = 1,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 26,
  [SMALL_STATE(7)] = 52,
  [SMALL_STATE(8)] = 78,
  [SMALL_STATE(9)] = 104,
  [SMALL_STATE(10)] = 130,
  [SMALL_STATE(11)] = 156,
  [SMALL_STATE(12)] = 182,
  [SMALL_STATE(13)] = 206,
  [SMALL_STATE(14)] = 230,
  [SMALL_STATE(15)] = 256,
  [SMALL_STATE(16)] = 283,
  [SMALL_STATE(17)] = 310,
  [SMALL_STATE(18)] = 337,
  [SMALL_STATE(19)] = 364,
  [SMALL_STATE(20)] = 391,
  [SMALL_STATE(21)] = 418,
  [SMALL_STATE(22)] = 430,
  [SMALL_STATE(23)] = 442,
  [SMALL_STATE(24)] = 454,
  [SMALL_STATE(25)] = 466,
  [SMALL_STATE(26)] = 478,
  [SMALL_STATE(27)] = 490,
  [SMALL_STATE(28)] = 502,
  [SMALL_STATE(29)] = 514,
  [SMALL_STATE(30)] = 526,
  [SMALL_STATE(31)] = 538,
  [SMALL_STATE(32)] = 553,
  [SMALL_STATE(33)] = 568,
  [SMALL_STATE(34)] = 583,
  [SMALL_STATE(35)] = 598,
  [SMALL_STATE(36)] = 613,
  [SMALL_STATE(37)] = 628,
  [SMALL_STATE(38)] = 643,
  [SMALL_STATE(39)] = 657,
  [SMALL_STATE(40)] = 671,
  [SMALL_STATE(41)] = 682,
  [SMALL_STATE(42)] = 693,
  [SMALL_STATE(43)] = 699,
  [SMALL_STATE(44)] = 705,
  [SMALL_STATE(45)] = 713,
  [SMALL_STATE(46)] = 719,
  [SMALL_STATE(47)] = 727,
  [SMALL_STATE(48)] = 735,
  [SMALL_STATE(49)] = 743,
  [SMALL_STATE(50)] = 751,
  [SMALL_STATE(51)] = 759,
  [SMALL_STATE(52)] = 767,
  [SMALL_STATE(53)] = 775,
  [SMALL_STATE(54)] = 783,
  [SMALL_STATE(55)] = 791,
  [SMALL_STATE(56)] = 799,
  [SMALL_STATE(57)] = 805,
  [SMALL_STATE(58)] = 813,
  [SMALL_STATE(59)] = 821,
  [SMALL_STATE(60)] = 829,
  [SMALL_STATE(61)] = 835,
  [SMALL_STATE(62)] = 843,
  [SMALL_STATE(63)] = 851,
  [SMALL_STATE(64)] = 855,
  [SMALL_STATE(65)] = 859,
  [SMALL_STATE(66)] = 863,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(4),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(37),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(12),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(3),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(33),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(13),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, .production_id = 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(9),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(57),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(6),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(49),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_reference, 2),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_reference, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_name, 2),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_name, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 5),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, .production_id = 5),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(32),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(38),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, .production_id = 4),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, .production_id = 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, .production_id = 4),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 4, .production_id = 4),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 3),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_option, 1, .production_id = 2),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_option, 1, .production_id = 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, .production_id = 1),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, .production_id = 1),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__variable_command, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [209] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tintin(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
