#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 6

enum {
  aux_sym_comment_token1 = 1,
  anon_sym_POUND = 2,
  aux_sym__variable_command_token1 = 3,
  aux_sym__variable_command_token2 = 4,
  sym_command_identifier = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_DOLLAR = 8,
  sym_string = 9,
  sym_word = 10,
  sym__semicolon = 11,
  sym_source_file = 12,
  sym__command_option = 13,
  sym_command = 14,
  sym_comment = 15,
  sym_variable_declaration = 16,
  sym__command_name = 17,
  sym__variable_command = 18,
  sym__block_choice = 19,
  sym_block = 20,
  sym_variable_reference = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_command_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_POUND] = "#",
  [aux_sym__variable_command_token1] = "command_identifier",
  [aux_sym__variable_command_token2] = "command_identifier",
  [sym_command_identifier] = "command_identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOLLAR] = "$",
  [sym_string] = "string",
  [sym_word] = "word",
  [sym__semicolon] = "_semicolon",
  [sym_source_file] = "source_file",
  [sym__command_option] = "_command_option",
  [sym_command] = "command",
  [sym_comment] = "comment",
  [sym_variable_declaration] = "command",
  [sym__command_name] = "_command_name",
  [sym__variable_command] = "_variable_command",
  [sym__block_choice] = "_block_choice",
  [sym_block] = "block",
  [sym_variable_reference] = "variable_reference",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym__variable_command_token1] = sym_command_identifier,
  [aux_sym__variable_command_token2] = sym_command_identifier,
  [sym_command_identifier] = sym_command_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_string] = sym_string,
  [sym_word] = sym_word,
  [sym__semicolon] = sym__semicolon,
  [sym_source_file] = sym_source_file,
  [sym__command_option] = sym__command_option,
  [sym_command] = sym_command,
  [sym_comment] = sym_comment,
  [sym_variable_declaration] = sym_command,
  [sym__command_name] = sym__command_name,
  [sym__variable_command] = sym__variable_command,
  [sym__block_choice] = sym__block_choice,
  [sym_block] = sym_block,
  [sym_variable_reference] = sym_variable_reference,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__variable_command_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__variable_command_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_command_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym__semicolon] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__command_option] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__command_name] = {
    .visible = false,
    .named = true,
  },
  [sym__variable_command] = {
    .visible = false,
    .named = true,
  },
  [sym__block_choice] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_name = 1,
  field_value = 2,
  field_variable_declaration = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
  [field_variable_declaration] = "variable_declaration",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_variable_declaration, 0, .inherited = true},
  [1] =
    {field_variable_declaration, 0},
  [2] =
    {field_variable_declaration, 0, .inherited = true},
    {field_variable_declaration, 1, .inherited = true},
  [4] =
    {field_name, 1},
    {field_value, 2},
  [6] =
    {field_variable_declaration, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 3,
  [8] = 8,
  [9] = 5,
  [10] = 8,
  [11] = 2,
  [12] = 4,
  [13] = 6,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 17,
  [18] = 15,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 19,
  [24] = 24,
  [25] = 20,
  [26] = 24,
  [27] = 22,
  [28] = 21,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 30,
  [34] = 29,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 38,
  [39] = 38,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 41,
  [46] = 46,
  [47] = 47,
  [48] = 46,
  [49] = 37,
  [50] = 47,
  [51] = 43,
  [52] = 44,
  [53] = 42,
  [54] = 54,
  [55] = 54,
  [56] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead == '}') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(2);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym__variable_command_token1);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__variable_command_token2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(15);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(12);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_command_identifier);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_command_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_string);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__semicolon);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [aux_sym__variable_command_token1] = ACTIONS(1),
    [aux_sym__variable_command_token2] = ACTIONS(1),
    [sym_command_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym__semicolon] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(56),
    [sym__command_option] = STATE(53),
    [sym_command] = STATE(53),
    [sym_comment] = STATE(53),
    [sym_variable_declaration] = STATE(45),
    [sym__command_name] = STATE(5),
    [sym__variable_command] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_comment_token1] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(17), 1,
      sym_word,
    ACTIONS(19), 1,
      sym__semicolon,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
    STATE(10), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [26] = 9,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    ACTIONS(27), 1,
      sym_string,
    STATE(9), 1,
      sym__command_name,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__variable_command,
    STATE(41), 1,
      sym_variable_declaration,
    STATE(42), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [56] = 6,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(36), 1,
      anon_sym_DOLLAR,
    ACTIONS(39), 1,
      sym_word,
    ACTIONS(29), 3,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
      sym__semicolon,
    STATE(4), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [80] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(44), 1,
      anon_sym_POUND,
    ACTIONS(46), 1,
      sym_word,
    ACTIONS(48), 1,
      sym__semicolon,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
    STATE(13), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [106] = 7,
    ACTIONS(52), 1,
      anon_sym_POUND,
    ACTIONS(54), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(58), 1,
      sym_word,
    ACTIONS(60), 1,
      sym__semicolon,
    ACTIONS(50), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
    STATE(4), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [132] = 9,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    ACTIONS(64), 1,
      sym_string,
    STATE(9), 1,
      sym__command_name,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__variable_command,
    STATE(41), 1,
      sym_variable_declaration,
    STATE(42), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [162] = 7,
    ACTIONS(54), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(58), 1,
      sym_word,
    ACTIONS(68), 1,
      anon_sym_POUND,
    ACTIONS(70), 1,
      sym__semicolon,
    ACTIONS(66), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
    STATE(4), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [188] = 7,
    ACTIONS(44), 1,
      anon_sym_POUND,
    ACTIONS(54), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(72), 1,
      sym_word,
    ACTIONS(74), 1,
      sym__semicolon,
    ACTIONS(42), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
    STATE(6), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [214] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(68), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      sym_word,
    ACTIONS(78), 1,
      sym__semicolon,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
    STATE(12), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [240] = 7,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(54), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(80), 1,
      sym_word,
    ACTIONS(82), 1,
      sym__semicolon,
    ACTIONS(9), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
    STATE(8), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [266] = 6,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(84), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_DOLLAR,
    ACTIONS(90), 1,
      sym_word,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      sym__semicolon,
    STATE(12), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [290] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(52), 1,
      anon_sym_POUND,
    ACTIONS(76), 1,
      sym_word,
    ACTIONS(93), 1,
      sym__semicolon,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
    STATE(12), 4,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
      aux_sym_command_repeat1,
  [316] = 8,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      aux_sym_comment_token1,
    ACTIONS(100), 1,
      anon_sym_POUND,
    STATE(5), 1,
      sym__command_name,
    STATE(14), 1,
      aux_sym_source_file_repeat1,
    STATE(32), 1,
      sym__variable_command,
    STATE(45), 1,
      sym_variable_declaration,
    STATE(53), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [343] = 8,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym__command_name,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__variable_command,
    STATE(41), 1,
      sym_variable_declaration,
    STATE(42), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [370] = 8,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    ACTIONS(105), 1,
      aux_sym_comment_token1,
    ACTIONS(108), 1,
      anon_sym_POUND,
    STATE(9), 1,
      sym__command_name,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__variable_command,
    STATE(41), 1,
      sym_variable_declaration,
    STATE(42), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [397] = 8,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym__command_name,
    STATE(14), 1,
      aux_sym_source_file_repeat1,
    STATE(32), 1,
      sym__variable_command,
    STATE(45), 1,
      sym_variable_declaration,
    STATE(53), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [424] = 8,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym__command_name,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym__variable_command,
    STATE(41), 1,
      sym_variable_declaration,
    STATE(42), 3,
      sym__command_option,
      sym_command,
      sym_comment,
  [451] = 2,
    ACTIONS(117), 1,
      anon_sym_POUND,
    ACTIONS(115), 6,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [463] = 2,
    ACTIONS(121), 1,
      anon_sym_POUND,
    ACTIONS(119), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [475] = 2,
    ACTIONS(125), 1,
      anon_sym_POUND,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [487] = 2,
    ACTIONS(129), 1,
      anon_sym_POUND,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [499] = 2,
    ACTIONS(117), 1,
      anon_sym_POUND,
    ACTIONS(115), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [511] = 2,
    ACTIONS(133), 1,
      anon_sym_POUND,
    ACTIONS(131), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [523] = 2,
    ACTIONS(121), 1,
      anon_sym_POUND,
    ACTIONS(119), 6,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [535] = 2,
    ACTIONS(133), 1,
      anon_sym_POUND,
    ACTIONS(131), 6,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [547] = 2,
    ACTIONS(129), 1,
      anon_sym_POUND,
    ACTIONS(127), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [559] = 2,
    ACTIONS(125), 1,
      anon_sym_POUND,
    ACTIONS(123), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      sym_word,
      sym__semicolon,
  [571] = 4,
    ACTIONS(54), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(135), 1,
      sym_word,
    STATE(27), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [586] = 4,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(137), 1,
      sym_word,
    STATE(36), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [601] = 4,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(139), 1,
      sym_word,
    STATE(33), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [616] = 4,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(141), 1,
      sym_word,
    STATE(30), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [631] = 4,
    ACTIONS(54), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(143), 1,
      sym_word,
    STATE(35), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [646] = 4,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_DOLLAR,
    ACTIONS(145), 1,
      sym_word,
    STATE(22), 3,
      sym__block_choice,
      sym_block,
      sym_variable_reference,
  [661] = 3,
    ACTIONS(149), 1,
      anon_sym_POUND,
    ACTIONS(151), 1,
      sym__semicolon,
    ACTIONS(147), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [672] = 3,
    ACTIONS(149), 1,
      anon_sym_POUND,
    ACTIONS(153), 1,
      sym__semicolon,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [683] = 2,
    ACTIONS(157), 1,
      anon_sym_POUND,
    ACTIONS(155), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [691] = 2,
    ACTIONS(52), 1,
      anon_sym_POUND,
    ACTIONS(50), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [699] = 2,
    ACTIONS(52), 1,
      anon_sym_POUND,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [707] = 1,
    ACTIONS(159), 3,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      sym_word,
  [713] = 2,
    ACTIONS(163), 1,
      anon_sym_POUND,
    ACTIONS(161), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [721] = 2,
    ACTIONS(167), 1,
      anon_sym_POUND,
    ACTIONS(165), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [729] = 2,
    ACTIONS(171), 1,
      sym_command_identifier,
    ACTIONS(169), 2,
      aux_sym__variable_command_token1,
      aux_sym__variable_command_token2,
  [737] = 2,
    ACTIONS(175), 1,
      anon_sym_POUND,
    ACTIONS(173), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [745] = 2,
    ACTIONS(163), 1,
      anon_sym_POUND,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [753] = 2,
    ACTIONS(68), 1,
      anon_sym_POUND,
    ACTIONS(66), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [761] = 2,
    ACTIONS(179), 1,
      anon_sym_POUND,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [769] = 2,
    ACTIONS(68), 1,
      anon_sym_POUND,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [777] = 2,
    ACTIONS(157), 1,
      anon_sym_POUND,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [785] = 2,
    ACTIONS(179), 1,
      anon_sym_POUND,
    ACTIONS(177), 2,
      aux_sym_comment_token1,
      anon_sym_RBRACE,
  [793] = 2,
    ACTIONS(181), 1,
      sym_command_identifier,
    ACTIONS(169), 2,
      aux_sym__variable_command_token1,
      aux_sym__variable_command_token2,
  [801] = 2,
    ACTIONS(175), 1,
      anon_sym_POUND,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [809] = 2,
    ACTIONS(167), 1,
      anon_sym_POUND,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      aux_sym_comment_token1,
  [817] = 1,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
  [821] = 1,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
  [825] = 1,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 80,
  [SMALL_STATE(6)] = 106,
  [SMALL_STATE(7)] = 132,
  [SMALL_STATE(8)] = 162,
  [SMALL_STATE(9)] = 188,
  [SMALL_STATE(10)] = 214,
  [SMALL_STATE(11)] = 240,
  [SMALL_STATE(12)] = 266,
  [SMALL_STATE(13)] = 290,
  [SMALL_STATE(14)] = 316,
  [SMALL_STATE(15)] = 343,
  [SMALL_STATE(16)] = 370,
  [SMALL_STATE(17)] = 397,
  [SMALL_STATE(18)] = 424,
  [SMALL_STATE(19)] = 451,
  [SMALL_STATE(20)] = 463,
  [SMALL_STATE(21)] = 475,
  [SMALL_STATE(22)] = 487,
  [SMALL_STATE(23)] = 499,
  [SMALL_STATE(24)] = 511,
  [SMALL_STATE(25)] = 523,
  [SMALL_STATE(26)] = 535,
  [SMALL_STATE(27)] = 547,
  [SMALL_STATE(28)] = 559,
  [SMALL_STATE(29)] = 571,
  [SMALL_STATE(30)] = 586,
  [SMALL_STATE(31)] = 601,
  [SMALL_STATE(32)] = 616,
  [SMALL_STATE(33)] = 631,
  [SMALL_STATE(34)] = 646,
  [SMALL_STATE(35)] = 661,
  [SMALL_STATE(36)] = 672,
  [SMALL_STATE(37)] = 683,
  [SMALL_STATE(38)] = 691,
  [SMALL_STATE(39)] = 699,
  [SMALL_STATE(40)] = 707,
  [SMALL_STATE(41)] = 713,
  [SMALL_STATE(42)] = 721,
  [SMALL_STATE(43)] = 729,
  [SMALL_STATE(44)] = 737,
  [SMALL_STATE(45)] = 745,
  [SMALL_STATE(46)] = 753,
  [SMALL_STATE(47)] = 761,
  [SMALL_STATE(48)] = 769,
  [SMALL_STATE(49)] = 777,
  [SMALL_STATE(50)] = 785,
  [SMALL_STATE(51)] = 793,
  [SMALL_STATE(52)] = 801,
  [SMALL_STATE(53)] = 809,
  [SMALL_STATE(54)] = 817,
  [SMALL_STATE(55)] = 821,
  [SMALL_STATE(56)] = 825,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(29),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(4),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(7),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(34),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(12),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(2),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(43),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(11),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(51),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, .production_id = 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 5),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, .production_id = 5),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_name, 2),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_name, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_reference, 2),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_reference, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, .production_id = 4),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, .production_id = 4),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 3),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__variable_command, 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_option, 1, .production_id = 2),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_option, 1, .production_id = 2),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, .production_id = 1),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, .production_id = 1),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, .production_id = 4),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 4, .production_id = 4),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [187] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tintin(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
